hypercube: Fix autoremove breakage on aarch64
Docker build fails on aarch64 with the following:

/var/tmp/rpm-tmp.CnRLJw: line 1: /usr/sbin/new-kernel-pkg: No such file
or directory
error: %preun(kernel-core-4.18.0-80.7.2.el7.aarch64) scriptlet failed,
exit status 127
Error in PREUN scriptlet in rpm package
kernel-core-4.18.0-80.7.2.el7.aarch64

The rootcause is the missing 'grubby' package in the CentOS docker
image we fetch from upstream, so install it before calling autoremove,
then clean it up later.

Signed-off-by: Alexandru Avadanii <Alexandru.Avadanii@enea.com>
Change-Id: I92e6529e6459b5570d6970a415a249c57aa5ecc3